<?php
clearstatcache();

$parse_uri = explode( 'wp-content', $_SERVER[ 'SCRIPT_FILENAME' ] );

require_once( $parse_uri[ 0 ] . 'wp-load.php' );


header( 'Content-type: application/xml' );


echo '<?xml version="1.0" encoding="UTF-8"?' . ">\n";


echo "<urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'>\n";

echo "<!-- Generated by SEO Pyramid -->";

$args = array( 'post_type' => array( 'page', 'post' ), 'post_status' => 'publish', 'posts_per_page' => -1, 'update_post_meta_cache' => 'false' );

$wpb_all_query = new\ WP_Query( $args );


?>

<?php if ( $wpb_all_query->have_posts() ) : ?>

<?php


while ( $wpb_all_query->have_posts() ): $wpb_all_query->the_post();

global $post;


$indeOrNot = get_post_meta( $post->ID, 'seo_pyramid_robots', true );


$seo_pyramid_sitemap_options = get_option( 'seo_pyramid_sitemap_option_name' );


if ( $indeOrNot !== "noindex, nofollow" ) {


  ?>

<url>

  <loc>

    <?php the_permalink(); ?>

  </loc>

  <?php if(!empty($seo_pyramid_sitemap_options['last_modified_2']))  { ?>

  <lastmod><?php echo get_the_modified_date('Y-m-d'); ?></lastmod>

  <?php } ?>

  <?php if(!empty($seo_pyramid_sitemap_options['change_frequency_0']) && get_post_meta( $post->ID, 'seo_pyramid_change_frequency', true )) { ?>

  <changefreq><?php echo get_post_meta( $post->ID, 'seo_pyramid_change_frequency', true ) ?></changefreq>

  <?php } ?>

  <?php if(!empty($seo_pyramid_sitemap_options['page_priority_1']) && get_post_meta( $post->ID, 'seo_pyramid_page_priority', true )){ ?>

  <priority><?php echo get_post_meta( $post->ID, 'seo_pyramid_page_priority', true ) ?></priority>

  <?php } ?>

</url>

<?php } endwhile; ?>

<?php wp_reset_query(); ?>

<?php else : ?>

<?php _e( 'Sorry, no posts matched your criteria.' ); ?>

<?php endif; ?>

<?php echo "</urlset>" ?>